In [4]:
import pathlib

filename = pathlib.Path.cwd().parent / 'data' / 'visceral_fat.csv'
filename

PosixPath('/home/fjayres/Dropbox/Insper/Disciplinas/MachineLearning/2023-1/sandbox/diabetes/data/visceral_fat.csv')

In [5]:
import pandas as pd

data = pd.read_csv(filename)

In [6]:
data

,number,age (years),ethnicity,diabetes mellitus,mean diastolic bp (mmhg),mean systolic bp (mmhg),central armellini fat (mm),current gestational age,pregnancies (number),first fasting glucose (mg/dl),bmi pregestational (kg/m),gestational age at birth,type of delivery,child birth weight (g),gestational dm
0,1,20,NaN,0,73.5,125.0,28.10,"12,1",1.0,NaN,33.20,"41,0",1,3840,0
1,2,28,0.0,0,75.5,112.0,43.10,"11,5",1.0,76.0,21.50,"39,1",0,2810,0
2,5,21,1.0,0,70.5,116.0,41.40,"12,6",1.0,86.0,21.41,"39,5",0,2455,0
3,9,25,0.0,0,92.5,167.0,39.60,"16,2",4.0,NaN,55.36,"39,4",0,3400,0
4,13,33,1.0,0,79.0,137.0,67.80,"11,2",2.0,86.0,30.85,"40,2",1,3930,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128,278,21,0.0,0,74.5,128.5,13.90,"10,4",2.0,81.0,21.22,"38,3",0,3775,0
129,280,22,0.0,0,84.0,125.0,69.05,"7,5",2.0,114.0,36.64,"37,3",1,3565,1
130,283,19,1.0,0,76.0,140.5,52.50,"20,0",2.0,88.0,23.62,"40,3",1,3260,0
131,285,23,1.0,0,83.5,122.5,31.45,"10,5",1.0,NaN,28.76,"40,6",1,3270,0
132,287,36,0.0,0,92.0,156.5,42.50,"8,5",4.0,NaN,44.43,"40,4",0,4226,0

In [9]:
def converte_idade_gestacional(texto):
    partes_do_texto = texto.split(',')
    semanas = int(partes_do_texto[0])
    dias = int(partes_do_texto[1])
    return 7*semanas + dias

data['current gestational age'] = data['current gestational age'].apply(converte_idade_gestacional)
data['gestational age at birth'] = data['gestational age at birth'].apply(converte_idade_gestacional)

In [10]:
data

,number,age (years),ethnicity,diabetes mellitus,mean diastolic bp (mmhg),mean systolic bp (mmhg),central armellini fat (mm),current gestational age,pregnancies (number),first fasting glucose (mg/dl),bmi pregestational (kg/m),gestational age at birth,type of delivery,child birth weight (g),gestational dm
0,1,20,NaN,0,73.5,125.0,28.10,85,1.0,NaN,33.20,287,1,3840,0
1,2,28,0.0,0,75.5,112.0,43.10,82,1.0,76.0,21.50,274,0,2810,0
2,5,21,1.0,0,70.5,116.0,41.40,90,1.0,86.0,21.41,278,0,2455,0
3,9,25,0.0,0,92.5,167.0,39.60,114,4.0,NaN,55.36,277,0,3400,0
4,13,33,1.0,0,79.0,137.0,67.80,79,2.0,86.0,30.85,282,1,3930,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128,278,21,0.0,0,74.5,128.5,13.90,74,2.0,81.0,21.22,269,0,3775,0
129,280,22,0.0,0,84.0,125.0,69.05,54,2.0,114.0,36.64,262,1,3565,1
130,283,19,1.0,0,76.0,140.5,52.50,140,2.0,88.0,23.62,283,1,3260,0
131,285,23,1.0,0,83.5,122.5,31.45,75,1.0,NaN,28.76,286,1,3270,0
132,287,36,0.0,0,92.0,156.5,42.50,61,4.0,NaN,44.43,284,0,4226,0

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133 entries, 0 to 132
Data columns (total 15 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   number                         133 non-null    int64
 1   age (years)                    133 non-null    int64
 2   ethnicity                      132 non-null    float64
 3   diabetes mellitus              133 non-null    int64
 4   mean diastolic bp (mmhg)       133 non-null    float64
 5   mean systolic bp (mmhg)        133 non-null    float64
 6   central armellini fat (mm)     133 non-null    float64
 7   current gestational age        133 non-null    int64
 8   pregnancies (number)           128 non-null    float64
 9   first fasting glucose (mg/dl)  103 non-null    float64
 10  bmi pregestational (kg/m)      132 non-null    float64
 11  gestational age at birth       133 non-null    int64
 12  type of delivery               133 non-null    int64
 13  child birth weight (g)         133 non-null    int64
 14  gestational dm                 133 non-null    int64
dtypes: float64(7), int64(8)
memory usage: 15.7 KB

In [12]:
data = data.drop(columns=['number', 'diabetes mellitus'])

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133 entries, 0 to 132
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   age (years)                    133 non-null    int64
 1   ethnicity                      132 non-null    float64
 2   mean diastolic bp (mmhg)       133 non-null    float64
 3   mean systolic bp (mmhg)        133 non-null    float64
 4   central armellini fat (mm)     133 non-null    float64
 5   current gestational age        133 non-null    int64
 6   pregnancies (number)           128 non-null    float64
 7   first fasting glucose (mg/dl)  103 non-null    float64
 8   bmi pregestational (kg/m)      132 non-null    float64
 9   gestational age at birth       133 non-null    int64
 10  type of delivery               133 non-null    int64
 11  child birth weight (g)         133 non-null    int64
 12  gestational dm                 133 non-null    int64
dtypes: float64(7), int64(6)
memory usage: 13.6 KB

In [17]:
data = data.dropna(axis=0)

In [18]:
data

,age (years),ethnicity,mean diastolic bp (mmhg),mean systolic bp (mmhg),central armellini fat (mm),current gestational age,pregnancies (number),first fasting glucose (mg/dl),bmi pregestational (kg/m),gestational age at birth,type of delivery,child birth weight (g),gestational dm
1,28,0.0,75.5,112.0,43.10,82,1.0,76.0,21.50,274,0,2810,0
2,21,1.0,70.5,116.0,41.40,90,1.0,86.0,21.41,278,0,2455,0
4,33,1.0,79.0,137.0,67.80,79,2.0,86.0,30.85,282,1,3930,1
5,18,0.0,67.5,111.5,26.80,89,1.0,80.3,22.60,287,0,2730,0
7,20,1.0,74.5,114.0,20.60,105,1.0,74.0,19.66,280,0,3610,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,17,1.0,76.5,126.0,38.60,122,1.0,78.0,26.22,287,0,3765,0
127,21,0.0,63.5,111.5,72.30,140,1.0,86.0,31.22,276,0,3155,0
128,21,0.0,74.5,128.5,13.90,74,2.0,81.0,21.22,269,0,3775,0
129,22,0.0,84.0,125.0,69.05,54,2.0,114.0,36.64,262,1,3565,1
130,19,1.0,76.0,140.5,52.50,140,2.0,88.0,23.62,283,1,3260,0